#
# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Samy Tafasca <samy.tafasca@idiap.ch>
#
# SPDX-License-Identifier: CC-BY-NC-4.0
#

# ==================================================================================================================== #
#                                                EXPERIMENT CONFIGURATION                                              #
# ==================================================================================================================== #


project:
    name: semgaze # name of the wandb project
    version: 1.0.0
    description: SemGaze - Transformer encoder-decoder architecture for gaze target localization and recognition.
    root: /home/elicer/semgaze # FILL ME

# ------------------------------------------------------------------------------------------------------------------- #

experiment:
    name: VAT Zero-Shot
    group: null
    task: test # test-only by default for zero-shot evaluation
    dataset: vat # gazefollow, gazehoi, vat

# ------------------------------------------------------------------------------------------------------------------- #

data:
    num_people: 1 # int or -1 to include all people
    image_size: 512
    heatmap_size: 64
    heatmap_sigma: 3
    return_head_mask: False
    vat:
        root: /home/elicer/semgaze/data/vat
        num_train_samples: 132563
        vocab_size: 1


# ------------------------------------------------------------------------------------------------------------------- #

model:
    semgaze:
        patch_size: 16
        token_dim: 768 # Decoder token dim (image encoder output is projected to this dim)
        image_size: ${data.image_size}
        gaze_vec_dim: 2
        image_encoder:
            name: facebook/dinov3-vitl16-pretrain-lvd1689m
            freeze: True
        image_to_decoder_proj:
            enabled: True
        decoder_depth: 2
        decoder_num_heads: 8
        temp_init_value: 0.07
    pretraining:
        gaze_backbone: /home/elicer/semgaze/weights/gaze360_resnet18.pt # FILL ME
    weights: null # keep null when evaluating from test.checkpoint

# ------------------------------------------------------------------------------------------------------------------- #

loss:
    weight_heatmap: 100
    weight_angular: 3

# ------------------------------------------------------------------------------------------------------------------- #

optimizer:
    lr: 2e-4
    weight_decay: 3e-3

# ------------------------------------------------------------------------------------------------------------------- #

scheduler:
    type: cosine_warmup # cosine_warmup (default), null (no scheduler)
    warmup_epochs: 4

# ------------------------------------------------------------------------------------------------------------------- #

train:
    seed: 10 # int or null for no seed
    matmul_precision: highest # highest (default), high, medium
    precision: bf16-mixed # 64, 32, 16, bf16-mixed
    epochs: 20
    batch_size: 300
    accumulate_grad_batches: 1
    device: cuda
    resume: False
    resume_from: null
    checkpointing:
        monitor: "metric/val/dist"
        mode: "min"
    freeze:
        gaze_encoder: False
        image_tokenizer: False
        gaze_decoder: False
    swa:
        use: True
        lr: 1e-5
        epoch_start: 17
        annealing_epochs: 3

# ------------------------------------------------------------------------------------------------------------------- #

val:
    checkpoint: null
    batch_size: 128
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

test:
    checkpoint: null # set this to a GF checkpoint for zero-shot VAT evaluation
    batch_size: 128
    device: ${train.device}
    l2_eval_mode: argmax # argmax (official-style), dark (optional)
    tta:
        enabled: False
        hflip: False

# ------------------------------------------------------------------------------------------------------------------- #

wandb:
    log: False
    entity: semgaze
    watch: all
    watch_freq: 500

# ------------------------------------------------------------------------------------------------------------------- #

hydra:
    run:
        dir: ./
    sweep:
        dir: ${hydra.run.dir}
        subdir: ${hydra.job.num}
    job:
        chdir: False
